# Generated by Django 5.1.2 on 2024-11-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=12)),
                ('customer_address', models.TextField(max_length=100)),
                ('customer_city', models.CharField(max_length=50)),
                ('customer_state', models.CharField(max_length=50)),
                ('customer_zip_code', models.CharField(max_length=6)),
                ('customer_country', models.CharField(max_length=50)),
                ('customer_registered', models.DateTimeField(auto_now_add=True)),
                ('customer_updated', models.DateTimeField(auto_now=True)),
                ('customer_verified', models.BooleanField(default=False, editable=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
